import { ProductRecord } from './product.types';

export const seedProducts: ProductRecord[] = [
  {
    id: 1,
    name: 'Legging Compressao Rose',
    cat: 'Parte de baixo',
    sub: 'Legging',
    price: 249.9,
    tag: 'Drop 01',
    icon: 'legging',
    rating: 4.9,
    reviews: 132,
    stock: 42,
    active: true,
    sizes: ['P', 'M', 'G', 'GG'],
    material: 'Suplex Power',
    pair: 2,
    sports: ['Musculacao', 'Yoga/Pilates', 'Funcional/HIIT'],
    colors: [
      { n: 'Rose', h: '#C94E82' },
      { n: 'Preto', h: '#2B1420' },
      { n: 'Blush', h: '#F0B9CD' },
    ],
    desc: 'Cintura alta com compressao media, sem transparencia no agachamento. Cos largo anatomico que nao enrola.',
  },
  {
    id: 2,
    name: 'Top Cropped Estrutura',
    cat: 'Top',
    sub: 'Top',
    price: 159.9,
    tag: 'Mais vendido',
    icon: 'top',
    rating: 4.8,
    reviews: 98,
    stock: 31,
    active: true,
    sizes: ['P', 'M', 'G'],
    material: 'Poliamida Dry',
    pair: 1,
    sports: ['Funcional/HIIT', 'Musculacao', 'Crossfit'],
    colors: [
      { n: 'Preto', h: '#2B1420' },
      { n: 'Rose', h: '#C94E82' },
      { n: 'Off-white', h: '#FBE3EB' },
    ],
    desc: 'Sustentacao media com bojo removivel e alcas regulaveis. Ideal para treino de forca e funcional.',
  },
  {
    id: 3,
    name: 'Shorts Biker Berry',
    cat: 'Parte de baixo',
    sub: 'Shorts',
    price: 169.9,
    tag: 'Drop 01',
    icon: 'shorts',
    rating: 4.7,
    reviews: 76,
    stock: 24,
    active: true,
    sizes: ['P', 'M', 'G', 'GG'],
    material: 'Suplex Power',
    pair: 4,
    sports: ['Corrida', 'Ciclismo', 'Funcional/HIIT'],
    colors: [
      { n: 'Berry', h: '#7A2246' },
      { n: 'Preto', h: '#2B1420' },
      { n: 'Blush', h: '#F0B9CD' },
    ],
    desc: 'Comprimento biker com silicone antideslizante na barra. Nao sobe durante o treino de pernas.',
  },
  {
    id: 4,
    name: 'Top Alta Sustentacao Candy',
    cat: 'Top',
    sub: 'Top',
    price: 189.9,
    tag: 'Alta performance',
    icon: 'top',
    rating: 4.9,
    reviews: 141,
    stock: 27,
    active: true,
    sizes: ['P', 'M', 'G', 'GG'],
    material: 'Poliamida Dry',
    pair: 3,
    sports: ['Corrida', 'Funcional/HIIT'],
    colors: [
      { n: 'Candy', h: '#C94E82' },
      { n: 'Preto', h: '#2B1420' },
    ],
    desc: 'Alta sustentacao para corrida e HIIT. Costas nadador e tecido com protecao UV50+.',
  },
  {
    id: 5,
    name: 'Calca Wide Leg Off-Duty',
    cat: 'Parte de baixo',
    sub: 'Calca',
    price: 279.9,
    tag: 'Athleisure',
    icon: 'wideleg',
    rating: 4.8,
    reviews: 63,
    stock: 18,
    active: true,
    sizes: ['P', 'M', 'G'],
    material: 'Moletom Peluciado',
    pair: 6,
    sports: ['Casual/Dia a dia'],
    colors: [
      { n: 'Blush', h: '#F0B9CD' },
      { n: 'Preto', h: '#2B1420' },
    ],
    desc: 'Do treino pro cafe. Modelagem wide leg com caimento fluido e cos alto.',
  },
  {
    id: 6,
    name: 'Regata Muscle Rosa',
    cat: 'Top',
    sub: 'Regata',
    price: 119.9,
    tag: '',
    icon: 'regata',
    rating: 4.8,
    reviews: 64,
    stock: 37,
    active: true,
    sizes: ['P', 'M', 'G', 'GG'],
    material: 'Algodao Premium',
    pair: 5,
    sports: ['Yoga/Pilates', 'Casual/Dia a dia'],
    colors: [
      { n: 'Rosa', h: '#E97FAB' },
      { n: 'Preto', h: '#2B1420' },
    ],
    desc: 'Regata muscle de caimento solto com cava ampla. Algodao penteado premium que nao deforma.',
  },
  {
    id: 7,
    name: 'Jaqueta Corta-Vento Candy',
    cat: 'Casaco',
    sub: 'Jaqueta',
    price: 399.9,
    tag: 'Edicao limitada',
    icon: 'jacket',
    rating: 5,
    reviews: 41,
    stock: 4,
    active: true,
    sizes: ['M', 'G'],
    material: 'Nylon Ripstop',
    pair: 1,
    sports: ['Corrida', 'Ciclismo'],
    colors: [
      { n: 'Preto', h: '#2B1420' },
      { n: 'Rose', h: '#C94E82' },
    ],
    desc: 'Corta-vento impermeavel com capuz embutido e bolsos com ziper.',
  },
  {
    id: 8,
    name: 'Meia Performance',
    cat: 'Acessorio',
    sub: 'Meia',
    price: 49.9,
    tag: '',
    icon: 'sock',
    rating: 4.6,
    reviews: 33,
    stock: 120,
    active: true,
    sizes: ['U'],
    material: 'Algodao Premium',
    pair: 1,
    sports: ['Musculacao', 'Corrida', 'Crossfit', 'Funcional/HIIT'],
    colors: [
      { n: 'Branco', h: '#FFF9FB' },
      { n: 'Preto', h: '#2B1420' },
    ],
    desc: 'Cano medio com reforco no calcanhar e amortecimento na sola.',
  },
];
