import { ProductRecord } from './product.types';

export const seedProducts: ProductRecord[] = [
  {
    id: 1,
    name: 'Legging Compressão Rose',
    cat: 'Shorts/Calça',
    sub: 'Legging',
    price: 249.9,
    promoPct: 0,
    tag: 'Drop 01',
    icon: 'legging',
    rating: 4.9,
    reviews: 132,
    stock: 42,
    active: true,
    sizes: ['P', 'M', 'G'],
    material: 'Suplex Power',
    pair: 2,
    sports: ['Musculação', 'Yoga/Pilates', 'Funcional/HIIT'],
    colors: [
      { n: 'Rose', h: '#C94E82' },
      { n: 'Preto', h: '#2B1420' },
      { n: 'Blush', h: '#F0B9CD' },
    ],
    desc: 'Cintura alta com compressão média, sem transparência no agachamento. Cós largo anatômico que não enrola.',
  },
  {
    id: 2,
    name: 'Top Cropped Estrutura',
    cat: 'Blusas/Top',
    sub: 'Top',
    price: 159.9,
    promoPct: 0,
    tag: 'Mais vendido',
    icon: 'top',
    rating: 4.8,
    reviews: 98,
    stock: 31,
    active: true,
    sizes: ['P', 'M', 'G'],
    material: 'Poliamida Dry',
    pair: 1,
    sports: ['Funcional/HIIT', 'Musculação', 'Crossfit'],
    colors: [
      { n: 'Preto', h: '#2B1420' },
      { n: 'Rose', h: '#C94E82' },
      { n: 'Off-white', h: '#FBE3EB' },
    ],
    desc: 'Sustentação média com bojo removível e alças reguláveis. Ideal para treino de força e funcional.',
  },
  {
    id: 3,
    name: 'Shorts Biker Berry',
    cat: 'Shorts/Calça',
    sub: 'Shorts',
    price: 169.9,
    promoPct: 0,
    tag: 'Drop 01',
    icon: 'shorts',
    rating: 4.8,
    reviews: 76,
    stock: 24,
    active: true,
    sizes: ['P', 'M', 'G'],
    material: 'Suplex Power',
    pair: 4,
    sports: ['Corrida', 'Ciclismo', 'Funcional/HIIT'],
    colors: [
      { n: 'Berry', h: '#7A2246' },
      { n: 'Preto', h: '#2B1420' },
      { n: 'Blush', h: '#F0B9CD' },
    ],
    desc: 'Comprimento biker com silicone antideslizante na barra. Não sobe durante o treino de pernas.',
  },
  {
    id: 4,
    name: 'Top Alta Sustentação Candy',
    cat: 'Blusas/Top',
    sub: 'Top',
    price: 189.9,
    promoPct: 0,
    tag: 'Alta performance',
    icon: 'top',
    rating: 4.9,
    reviews: 141,
    stock: 27,
    active: true,
    sizes: ['P', 'M', 'G'],
    material: 'Poliamida Dry',
    pair: 3,
    sports: ['Corrida', 'Funcional/HIIT'],
    colors: [
      { n: 'Candy', h: '#C94E82' },
      { n: 'Preto', h: '#2B1420' },
    ],
    desc: 'Alta sustentação para corrida e HIIT. Costas nadador e tecido com proteção UV50+.',
  },
  {
    id: 5,
    name: 'Calça Wide Leg Off-Duty',
    cat: 'Shorts/Calça',
    sub: 'Calça',
    price: 279.9,
    promoPct: 0,
    tag: 'Athleisure',
    icon: 'wideleg',
    rating: 4.8,
    reviews: 63,
    stock: 18,
    active: true,
    sizes: ['P', 'M', 'G'],
    material: 'Moletom Peluciado',
    pair: 6,
    sports: ['Casual/Dia a dia'],
    colors: [
      { n: 'Blush', h: '#F0B9CD' },
      { n: 'Preto', h: '#2B1420' },
    ],
    desc: 'Do treino para o café. Modelagem wide leg com caimento fluido e cós alto.',
  },
  {
    id: 6,
    name: 'Regata Muscle Rosa',
    cat: 'Blusas/Top',
    sub: 'Regata',
    price: 119.9,
    promoPct: 0,
    tag: '',
    icon: 'regata',
    rating: 4.8,
    reviews: 64,
    stock: 37,
    active: true,
    sizes: ['P', 'M', 'G'],
    material: 'Algodão Premium',
    pair: 5,
    sports: ['Yoga/Pilates', 'Casual/Dia a dia'],
    colors: [
      { n: 'Rosa', h: '#E97FAB' },
      { n: 'Preto', h: '#2B1420' },
    ],
    desc: 'Regata muscle de caimento solto com cava ampla. Algodão penteado premium que não deforma.',
  },
  {
    id: 7,
    name: 'Jaqueta Corta-Vento Candy',
    cat: 'Casaco',
    sub: 'Jaqueta',
    price: 399.9,
    promoPct: 0,
    tag: 'Edição limitada',
    icon: 'jacket',
    rating: 5,
    reviews: 41,
    stock: 4,
    active: true,
    sizes: ['M', 'G'],
    material: 'Nylon Ripstop',
    pair: 1,
    sports: ['Corrida', 'Ciclismo'],
    colors: [
      { n: 'Preto', h: '#2B1420' },
      { n: 'Rose', h: '#C94E82' },
    ],
    desc: 'Corta-vento impermeável com capuz embutido e bolsos com zíper.',
  },
  {
    id: 8,
    name: 'Meia Performance',
    cat: 'Acessório',
    sub: 'Meia',
    price: 49.9,
    promoPct: 0,
    tag: '',
    icon: 'sock',
    rating: 4.8,
    reviews: 33,
    stock: 120,
    active: true,
    sizes: ['U'],
    material: 'Algodão Premium',
    pair: 1,
    sports: ['Musculação', 'Corrida', 'Crossfit', 'Funcional/HIIT'],
    colors: [
      { n: 'Branco', h: '#FFF9FB' },
      { n: 'Preto', h: '#2B1420' },
    ],
    desc: 'Cano médio com reforço no calcanhar e amortecimento na sola.',
  },
];
